tungbq/devops-toolkit

.github/workflows/docker-image.yml
Part of: #9
- Create docker-image.yml
- Build the docker image on PR to ensure no breakage
=> ci: Create docker-image.yml workflow

README.md
Related: #17 
- add todo feature
=> doc: add todo feature

.github/workflows/dockerfile-lint.yml
Closes: #22
- add new dockerfile-lint workflow
- using https://github.com/hadolint/hadolint
=> ci: add new dockerfile-lint workflow

.github/workflows/docker-image.yml
Closes: #30
- add Verify tool versions step
- call script created via #29 (#28)
=> ci: add verify tool versions step

Dockerfile, scripts/check_version_in_toolkit.sh
Closes: #37 
- helm: add helm to the toolkit
=> helm: add helm to the toolkit

.github/workflows/docker-image.yml
Closes: #14 
- Define the list of paths that impact to the CI process
=> ci: config path in docker-image.yml

README.md
Closes: #48 
- doc: add the tool versions in toolkit
=> doc: add the tool versions in toolkit

README.md
=> doc: add the tool versions in toolkit.v2.base.image

README.md
doc: add pull dockerhub command
=> doc: add pull dockerhub command

.github/workflows/docker-image.yml
=> ci: Push image debug

.github/workflows/docker-image.yml
Related #46 
Push latest main with SHA
=> ci: implement push latest image process

.github/workflows/docker-image.yml
Reverts tungbq/devops-toolkit#58
=> Revert "ci: Push image debug"

.github/workflows/docker-image-ci.yml, .github/workflows/docker-image-main.yml
Closes: #63
- release: implement ci for main push
=> release: implement ci for main push

README.md
Closes: #67 
- doc: add docker main workflow status badge
=> doc: add docker main workflow status badge

README.md
=> fix: ansible guide typo

README.md
=> doc: enhance guideline

README.md
=> Correct Docker Hub title

.github/workflows/docker-image-ci.yml, .github/workflows/dockerfile-lint.yml
Closes: #86 
ci: Abort the previous running CI workflow in the same pull request
=> ci: Abort the previous running CI workflow in the same pull request

.github/workflows/auto-labeler.yml
Bug from: #88
- ci: fix Invalid event type: issues
=> ci: fix Invalid event type: issues

.github/workflows/auto-labeler.yml
Bug from #24 
- ci/bug: fix the label format
=> ci/bug: fix the label format list

README.md
doc: Add link to dockerhub image
=> doc: Add link to dockerhub image

Dockerfile
Part of: #104 
- core: optimize the image size
=> core: optimize the image size

README.md, docs/troubleshooting/TROUBLESHOOTING.md, docs/usage/README.md, docs/usage/ansible_usage.md, docs/usage/python_usage.md
part of #109 
doc: ansible user guide
=> doc: ansible user guide

docs/usage/ansible_usage.md
=> doc: ansible doc fix

.github/workflows/auto-labeler.yml
ci: fix labeling list
from `docs` to `doc`
=> ci: fix labeling list

docs/usage/kubectl_usage.md
=> doc: update the kubectl usage

docs/usage/README.md
related #109 
doc: add helm usage to main document
=> doc: add helm usage to main document

README.md
=> doc: Update README.md icon

README.md, docs/build/build_toolkit_image.md
doc: improve the project introduction
=> doc: improve the project introduction

README.md
doc: add usage to tool table
Related #126
=> doc: add usage to tool table

.github/workflows/greeting.yml
ci: Add Greetings CI to welcome new contributors
=> ci: Add Greetings CI to welcome new contributors

README.md
=> doc: Add docker pull badge

README.md
Closes: ##71
This task is to update the content of README.md, change as below:
from:
- Feel free to open a new issue if you want to request more content about DevOps Dockerfile
to:
- Feel free to open a new issue if you encounter the toolkit bug or want to request more content about DevOps toolkit- DescribeYourChangeHere
=> [UPDATED] readme.me - open instruction

README.md
=> doc: description improvement

.github/workflows/dockerhub-description.yml
Closes: #131 
- ci: Create dockerhub-description.yml
- to automate dockerhub description
=> ci: Create dockerhub-description.yml

.github/workflows/dockerhub-description.yml
ci: Update dockerhub-description.yml to use token
=> ci: Update dockerhub-description.yml to use token

.github/workflows/dockerhub-description.yml
Related #131 
ci: Run dockerhub-description.yml on main push event
=> ci: Run dockerhub-description.yml on main push event

README.md
doc: update dockerhub hyperlink in README.md
=> doc: update dockerhub hyperlink in README.md

.github/workflows/release-docker-image-main.yml
=> ci: enable url completion

.github/workflows/auto-labeler.yml, .github/workflows/dockerfile-lint.yml
Closes: #103
- [Added more labels to support list, in the auto-labeler.yml
=> Added more labels to support list

README.md
Decorate to the project description with  🐳 icon
=> Decorate to the project description with  🐳 icon

README.md
=> doc: Add tagging guide

README.md
=> doc: remove duplicated lines

README.md
bug: fix action badge status in README.md
=> bug: fix action badge status in README.md

README.md
=> doc: add release badge

Dockerfile
Install SSH client.
Support ansible running on remote SSH VM
=> Install SSH client

README.md
Closes: #187 
doc: update instruction
=> doc: update instruction

README.md
=> Adjust node in quick start section

scripts/check_version_in_toolkit.sh
Add step to verify pwsh version in toolkit.
This is a follow up PR for #192 
Changes
- Add pwsh version verification into `scripts/check_version_in_toolkit.sh`
=> Verify pwsh version in toolkit

README.md
=> Add PS_VERSION to main page

README.md, docs/usage/ansible_usage.md, docs/usage/awscli_usage.md, docs/usage/azurecli_usage.md, docs/usage/helm_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/run_mode.md, docs/usage/terraform_usage.md, entrypoint.sh
Closes: #203 
Improve the configuration path name
Use `/.dtc` for config path
=> Improve the devops toolkit configuration path name

README.md, devops-toolkit
=> Provide the devops-toolkit execution script

README.md, docs/usage/ansible_usage.md, docs/usage/awscli_usage.md, docs/usage/azurecli_usage.md, docs/usage/devops_toolkit_cli.md, docs/usage/helm_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/terraform_usage.md
=> Update tool usage for devops-toolkit-cli approach

README.md, devops-toolkit-cli
=> Improve the CLI document and add step to confirm cleanup

README.md
=> Document update for usage

README.md, devops-toolkit-cli
=> Support multiple devops-toolkit in CLI

README.md
=> docs: Add cleanup --all note

README.md, devops-toolkit-cli
=> cli: Add missing function

README.md
=> doc: Update get started doc

.gitignore, README.md, demo/README.md, demo/provistion-azure-vm/.terraform.lock.hcl, demo/provistion-azure-vm/README.md, demo/provistion-azure-vm/main.tf, demo/provistion-azure-vm/output.tf, demo/provistion-azure-vm/providers.tf, demo/provistion-azure-vm/ssh.tf, demo/provistion-azure-vm/variables.tf
=> Add devops-toolkit demo create Azure VM via terraform

demo/provistion-azure-vm/README.md
=> Add cleanup in post demo section

README.md, demo/README.md
=> Add demo icon 📺

README.md
Add document to run with tool config from host
=> Add document to run with tool config from host

.github/workflows/toolkit-updater.yaml
=> Update toolkit-updater.yaml timer
