Dockerfile, README.md, docs/TROUBLESHOOTING.md
Closes: #3
- Initialize the Dockerfile
- Using ubuntu:22.04
- Install devtools
- Install python3/pip3
- Build 🆗:
```
PS D:\CODING\GITHUB\OPEN-SOURCE\my-project\devops-toolkit> docker run --rm devops-toolkit python3 --version
Python 3.11.3
PS D:\CODING\GITHUB\OPEN-SOURCE\my-project\devops-toolkit> docker run --rm devops-toolkit pip3 --version   
pip 24.0 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
```
=> docker: add new Dockerfile with ubuntu based

Dockerfile, scripts/docker_build.sh
Related: #12 
- Add ansible core
Verify build ✔️:
```bash
PS D:\CODING\GITHUB\OPEN-SOURCE\my-project\devops-toolkit> docker run --rm devops-toolkit ansible --version    
ansible [core 2.16.4]
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible
python version = 3.11.3 (main, Feb 27 2024, 16:35:52) [GCC 11.4.0] (/usr/local/bin/python3)
jinja version = 3.1.3
libyaml = True
```
=> ansible: add ansible-core to the toolkit

Dockerfile
Closes: #21
- Use `ARG TERRAFORM_VERSION=1.7.4`
- add terraform to the toolkit
- support customize version
=> docker: add terraform to the toolkit

.github/workflows/docker-image.yml, Dockerfile, docs/TROUBLESHOOTING.md, scripts/check_version_in_toolkit.sh
Closes: #23 
- add kubectl to the toolkit
- use: `ARG KUBECTL_VERSION=1.29.2`
=> docker: add kubectl to the toolkit

Dockerfile, README.md, scripts/check_version_in_toolkit.sh
Closes: #39 
- core: add aws cli to toolkit
=> core: add aws cli to toolkit

README.md
=> doc: Update image name in README.md

README.md
=> doc: improvement README.md

README.md
Closes: #52
- usage: create doc to guide user build custom version of the toolkit
=> usage: create doc to guide user build custom version of the toolkit

README.md
=> doc: enhancement the usage

.github/workflows/docker-image-main.yml
Closes: #65 
ci: only support manual release for now
read the deployment pricing document and enable auto release later
=> ci: only support manual release for now

Dockerfile, README.md, scripts/check_version_in_toolkit.sh
Closes: #40 
- add Azure to the toolkit
- Version 2.57.0
=> feat/azure: add Azure to the toolkit

Dockerfile, README.md, scripts/check_version_in_toolkit.sh
Closes: #78 
- upgrade tool to latest version
=> core: update tool versions

.github/workflows/toolkit-updater.yaml
Related: #88 
- ci: Update toolkit-updater.yaml using PAT due to github security
=> ci: Update toolkit-updater.yaml using PAT

.github/workflows/docker-image-ci.yml, .github/workflows/docker-image-main.yml, Dockerfile, README.md, samples/README.md, samples/ansible/check_os.yml, samples/python/rectangle_area_calculator.py, samples/run_sample.sh, samples/terraform/basic/main.tf
Related: #70 
samples: Add tooling sample code
- ansible, terraform, python
- add the run sample step to CI
- document provided
=> sample: Add tooling sample code to toolkit

.github/workflows/dockerfile-lint.yml
ci: rename dockerfile lint workflow
From `build` to `dockerfile-lint`
=> ci: rename dockerfile lint workflow

.github/workflows/auto-labeler.yml, .github/workflows/docker-image-ci.yml, .github/workflows/issue-labeler.yml
Closes: #24 
- ci: implement auto labeler for new PR and issue
- only works for the support labels (to avoid spamming label in this repo)
- limit the scope of docker image CI trigger to save resources
- It will run on events:
```yaml
on:
issues:
types:
- reopened
- opened
- edited
pull_request:
types:
- reopened
- opened
- edited
````
=> ci: implement auto labeler for new PR and issue

README.md
doc: running with host network instruction
=> doc: running with host network instruction

docs/others/README.md, docs/usage/README.md, docs/usage/python_usage.md, docs/usage/terraform_usage.md
Related #109 
- doc: add terraform usage
=> doc: add terraform usage

docs/usage/README.md, docs/usage/ansible_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/terraform_usage.md
Subtask of #109 
doc: add the kubectl usage
Add more docs to other tooling usage
=> doc: add the kubectl usage

docs/usage/helm_usage.md, docs/usage/kubectl_usage.md
Subtask of #109 
doc: update the helm usage.
link to k8s as prerequisite.
=> doc: update the helm usage

docs/usage/README.md, docs/usage/awscli_usage.md
Related #109 
doc: aws cli usage
=> doc: aws cli usage

docs/usage/README.md, docs/usage/azurecli_usage.md
related #109 
doc: add azure cli usage
=> doc: add azure cli usage

README.md
=> doc: improve the project doc

samples/README.md
Hi Tung, does this answer the ticket?
Add the sample code from samples/run_sample.sh to samples/README.md #96
Also, should I add the installation to the script? (from https://charts.bitnami.com/) I guess something like:
helm install sample-release bitnami/| grep jenkins
Closes: #96 
=> doc: Update samples README.md

Dockerfile, README.md, docs/build/build_toolkit_image.md, scripts/check_latest_version.py, toolkit_info.json
Part of: #104 
Improve the image size and build time🔥 
- core/improve: install python with apt
- remove unnecessary build tool
- use python3.11 in the toolkit
- faster build time
Improvement result:
- size: from  `2.11 GB` -> `1.41 GB` ✔️ 
- time: from `5m` -> `53s` ⌚
=> core: optimize the image size and build time 🔥

.github/workflows/deploy-docker-image-main.yml, .github/workflows/deploy-docker-image-release.yml, .github/workflows/release-docker-image-tag.yml
ci: add release pipeline
- Run on every tag `v.*` created
- Push image `tungbq/devops-toolkit:X.Y.Z` to DockerHub (with X.Y.Z is the tag version from a repo release (tag repo vX.Y.Z)
=> ci: add release pipeline

.github/workflows/dockerfile-lint.yml
Closes: #145
- Update `dockerfile-lint.yml` workflow to trigger only on Dockerfile changes.
=> Update Dockerfile Lint workflow to trigger only on Dockerfile changes

docs/usage/ansible_usage.md, docs/usage/awscli_usage.md, docs/usage/azurecli_usage.md, docs/usage/helm_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/terraform_usage.md, samples/README.md
Ansible document improvement and minor change image name
=> Ansible document improvement and minor change image name

.github/workflows/deploy-docker-image-release.yml
@tungbq 
Hi!
The following changes have been made. Please review them and provide your feedback.
Closes: #175 
- `.github/workflows/deploy-docker-image-release.yml`
-  Replaced the deprecated `set-output` command with the new `$GITHUB_ENV` method to set environment variables across steps in the workflow.
=> Update deploy-docker-image-release.yml to replace deprecated set-output

Dockerfile, README.md, docs/usage/ansible_usage.md, docs/usage/awscli_usage.md, docs/usage/azurecli_usage.md, docs/usage/helm_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/run_mode.md, docs/usage/terraform_usage.md, entrypoint.sh
Related: #156
Enable container configuration reusable:
- Mounts a config folder on the host to the container.
- This allows reusing configurations in the container, like AWS and Azure login sessions, ...
- Update related document
- Add entrypoint to Dockerfile
=> feat: Enable toolkit container configuration reusable

README.md, devops-toolkit
Related #209 - documentation task
Add init feature to init the devops-toolkit with latest or specific versions
=> Add document for the execution script

README.md, devops-toolkit-cli
Related #207 - Improvement
This helps us separate the cli and the image name, avoid confusing
=> Rename devops-toolkit to devops-toolkit-cli

docs/usage/ansible_usage.md, docs/usage/awscli_usage.md, docs/usage/azurecli_usage.md, docs/usage/helm_usage.md, docs/usage/kubectl_usage.md, docs/usage/python_usage.md, docs/usage/terraform_usage.md
=> Align focument with new cli feature
